[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[functions]
  directory = "netlify/functions"
  # specify timeouts
  [functions.openai-background]
    timeout = 500
    maxDuration = 500
